env:
  GRAFANA_URL: https://inside.beeline.ru
  GRAFANA_ACCESS_TOKEN: "vault:eafdmmart/data/dev/grafana#token"
  E2E_TEMPLATE_URL: https://inside.beeline.ru/d/82vrNvDvk/cj-template?orgId=1
  DEFAULT_METRIC_SOURCE: https://inside.beeline.ru/d/hwzG1EcNz/opensearch-template-api-queries?orgId=1
  E2E_FOLDER: https://inside.beeline.ru/dashboards/f/CuisNDDDz/fdm-cj
  NODE_TLS_REJECT_UNAUTHORIZED: '0'
  API_PORT: '8080'
  PRODUCT_SERVICE_URL: https://fdm-products-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  CX_SERVICE_HEADER: "{ \"user-roles\": [\"DEFAULT\",\"ADMINISTRATOR\"],\"user-permission\": [\"DESIGN_ARTIFACT\",\"CREATE_ARTIFACT\",\"EDIT_ARTIFACT\",\"DELETE_ARTIFACT\"],\"user-id\": 1, \"user-products-ids\": [1]}"
  CX_SERVICE_URL: https://cx-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru


ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault-test.vimpelcom.ru/"